### ISSUE TITLE
ABOUT code

### ISSUE THREAD

**Issue by LINFF1023** [Nickkzz97/Endoscopy-single-image-depth-estimation-using-self-supervised-method#1]
hiiiiiii,
Isn't this Liu's code? What is this code for?

**Comment by Nickkzz97** [comment]
Hello!
Yeah, it is.
For a project, we have compared how models for natural datasets perform poorly on endoscopic datasets compared to the one where it is considering sparse points generated by SFM. It's an experimental and comparison-based study.
